### ISSUE TITLE
Miscolored text in Donkey Kong Heart Hunt's HUD

### ISSUE THREAD

**Issue by Superjustinbros** [10yard/dkafe#8]
![0000](https://github.com/10yard/dkafe/assets/4167951/823df242-40fa-4ff3-9549-fd6cc856575b)

In Donkey Kong Heart Hunt, the top left number in the target scores/prize amounts is colored blue instead of the intended red.

**Comment by 10yard** [comment]
Well spotted!  This issue is resolved in the latest commit.

DK has 2 colour palettes per character.  The original author of this hack (Paul Goes) makes use of pink and blue for that particular piece of text.  My workaround is draw 3 red boxes to form the character "1" in that location when playing DK Heart Hunt.

	screen:draw_box(256, 172, 249, 174, 0, _red) -- vertical line
	screen:draw_box(250, 170, 249, 176, 0, _red) -- horizontal line near top
	screen:draw_box(255, 171, 254, 172, 0, _red) -- horizontal line at bottom
